[package]
name = "faucet_pool"
version = "1.0.0"
authors = ["Faucet Team"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
faucet_pool = "0x0"
sui = "0x2"